### ISSUE TITLE
GPU Device and Runtime

### ISSUE THREAD

**Issue by qw85639229** [HelmholtzAI-FZJ/flex_gen#1]
Great work on this project! Could you please share which GPU you used and how long the training time took?

Thanks!

**Comment by rakkit** [comment]
Hi, most models (except the model size scaling) discussed in the paper are small-size, F8/F16 models have 70-80M parameters.  
As we discussed in the paper, we need ~ 20 epochs of training, so for 256x256 resolution case, if you have limited GPUs, e.g. 16-32 40GB GPUs, I would suggest going 256 Batch size train it within one day or even faster.   If you have enough GPUs, e.g. > 64x80GB GPUs, training can done within a few hours with a 512 Batch size.  You can plugin in the activation checkpoint in case you run out of memory,  this wouldn't hurt training speed that much.

the larger model ~160M, e.g. same size as (open) MagvitV2 need 1.3-1.5x longer time for training.

**Comment by qw85639229** [comment]
Thank you very much for your response💗! I have another question: in the `vae_baseline_no_tricks.yaml` file, is the `train_batch_size` the batch size per single GPU? If I train on a single machine with 8 GPUs, should the corresponding `total_batch_size` be \(16 x 8 = 128\)? If I train for 20 epochs, the calculation would be:

1281167(imagenet train data file num) x 20 / 128 = 200182

Should I then set `num_train_steps` to 200,000?

Additionally, I noticed that `use_distributed_sampler` is not enabled in the code. Is there a specific reason for this?

**Comment by rakkit** [comment]
Hi, yes, the num_train_steps (also eval) should be scaled with respect to batch size, 200k is correct in your case. 
`vae_baseline_no_tricks.yaml` is the baseline config with vae only, this might gives a bad results.

Accelerator will handle the DDP and distributed data sampler train `Trainer`, we don't have to manually enable the distributed sampler for data loader.
