### ISSUE TITLE
ModuleNotFoundError: No module named 'flex_gen.layers.linear_attention'

### ISSUE THREAD

**Issue by zxytim** [HelmholtzAI-FZJ/flex_gen#3]
https://github.com/HelmholtzAI-FZJ/flex_gen/blob/main/flex_gen/layers/__init__.py#L1

```python
from .linear_attention import *
```

But there's no `linear_attention.py` in `layers` directory

**Comment by rakkit** [comment]
fixed. https://github.com/HelmholtzAI-FZJ/flex_gen/commit/dc75396ef7ae8e6cccdb56e417114dd6108c2258

we can remove it as we did not use linear_attention.

thanks for reporting the bug
